// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9hoUsrU-Kfwnfq40YLGiuQnSklzs-ySI',
    appId: '1:153749149171:web:8db143d62f247091f26e86',
    messagingSenderId: '153749149171',
    projectId: 'kelimemayinlari2',
    authDomain: 'kelimemayinlari2.firebaseapp.com',
    storageBucket: 'kelimemayinlari2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIljX-7HdjhKLqiwm_MMQ-S3Jt6eQaxJc',
    appId: '1:153749149171:android:c82336452e225cfdf26e86',
    messagingSenderId: '153749149171',
    projectId: 'kelimemayinlari2',
    storageBucket: 'kelimemayinlari2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZIC_5hbkiS_VtHaIXJ8Kvsiwr8SyXqQ',
    appId: '1:153749149171:ios:37a5edcec9f40031f26e86',
    messagingSenderId: '153749149171',
    projectId: 'kelimemayinlari2',
    storageBucket: 'kelimemayinlari2.firebasestorage.app',
    iosBundleId: 'com.example.kelimeMayinlari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTZIC_5hbkiS_VtHaIXJ8Kvsiwr8SyXqQ',
    appId: '1:153749149171:ios:37a5edcec9f40031f26e86',
    messagingSenderId: '153749149171',
    projectId: 'kelimemayinlari2',
    storageBucket: 'kelimemayinlari2.firebasestorage.app',
    iosBundleId: 'com.example.kelimeMayinlari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9hoUsrU-Kfwnfq40YLGiuQnSklzs-ySI',
    appId: '1:153749149171:web:5c98b9f0bb0e34d9f26e86',
    messagingSenderId: '153749149171',
    projectId: 'kelimemayinlari2',
    authDomain: 'kelimemayinlari2.firebaseapp.com',
    storageBucket: 'kelimemayinlari2.firebasestorage.app',
  );

}